"""add ticket category

Revision ID: 1ece6cbeede6
Revises: 06c6ad9f916b
Create Date: 2026-09-01 12:37:47.902561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ece6cbeede6'
down_revision: Union[str, Sequence[str], None] = '06c6ad9f916b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('category', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'category')
    # ### end Alembic commands ###
